# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd6fb7a88339159361ef6e3e9405e8b8c72922008b5ae65e5e3c20faf23b4eadc8deae137ddaff0e76f9a9f3117bc9e127bfd65f17c1234544c2ac9cd7da30c

test:
  secret_key_base: b2a1ae8b5e9f7989119703b301b46f2dc219f12535436d128edccf9d0b0d373faa3d0339324dd3b733d6be339b0e02cb74401d12a11c0c7344f7293f0a6a2dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
